export const MESSAGES_RECIEVED = 'MESSAGES_RECIEVED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ERROR_CATCH = 'ERROR_CATCH';
export const ERROR_CLEAR = 'ERROR_CLEAR';
export const UPDATE_LAST_MESSAGE_DATE = 'UPDATE_LAST_MESSAGE_DATE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const LIKE_TOGGLE = 'LIKE_TOGGLE';